# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHub Gists' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub Gists
  pod 'Alamofire'

end
